default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planitint_development
  username: postgres
  password: asdasd123
  host: localhost

test:
  <<: *default
  database: planitint_test
  host: localhost

production:
  <<: *default
  database: planitint_production
  password: <%= ENV['PLANIT_DATABASE_PASSWORD'] %>
