default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planit_development
  username: postgres
  password: asdasd123
  host: localhost
  
test:
  <<: *default
  database: planit_test
  host: localhost

production:
  <<: *default
  database: planit_production
  username: postgres
  password: <%= ENV['PLANIT_DATABASE_PASSWORD'] %>
